[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/data"
  to = "/.netlify/functions/data"
  status = 200

[[redirects]]
  from = "/api/restaurant"
  to = "/.netlify/functions/restaurant"
  status = 200

[[redirects]]
  from = "/"
  to = "/.netlify/functions/hello"
  status = 200
